// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw6y93ISx6yf2dqrVoQsOBOuZ3nitK2vA',
    appId: '1:1089529898783:web:0ffc7e4c49546f3db2f22a',
    messagingSenderId: '1089529898783',
    projectId: 'flash-chat-bdcde',
    authDomain: 'flash-chat-bdcde.firebaseapp.com',
    storageBucket: 'flash-chat-bdcde.appspot.com',
    measurementId: 'G-9XMZ0KN6PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_gIKxrLKTWoEcyJkYP0rbuX9ysIGsZVU',
    appId: '1:1089529898783:android:3a44c4f55600c5fcb2f22a',
    messagingSenderId: '1089529898783',
    projectId: 'flash-chat-bdcde',
    storageBucket: 'flash-chat-bdcde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz5zyw3fn4tf_94zCDkhM1VQZwB5yXtnA',
    appId: '1:1089529898783:ios:e7ad98d650f674dab2f22a',
    messagingSenderId: '1089529898783',
    projectId: 'flash-chat-bdcde',
    storageBucket: 'flash-chat-bdcde.appspot.com',
    iosClientId: '1089529898783-72ohh7bljjtm83qne7gq2uaidinfojb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz5zyw3fn4tf_94zCDkhM1VQZwB5yXtnA',
    appId: '1:1089529898783:ios:f56a25cd621e4db6b2f22a',
    messagingSenderId: '1089529898783',
    projectId: 'flash-chat-bdcde',
    storageBucket: 'flash-chat-bdcde.appspot.com',
    iosClientId: '1089529898783-9c65a077rld8pddthqh2b98uvgducvg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
